---
replicaCount: 1

image:
  backend:
    repository: docker.io/gangadhar369/myapp-backend
    tag: "2389fdf81ca645370cc94011366338e72a4a336f"
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/gangadhar369/myapp-frontend
    tag: "2389fdf81ca645370cc94011366338e72a4a336f"
    pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  user: postgres
  password: postgres
  database: appdb
  persistence:
    enabled: true
    size: 1Gi

