---
replicaCount: 1

image:
  backend:
    repository: docker.io/gangadhar369/myapp-backend
    tag: "4f9029657e3ae6472c6a985e78b19dc9e822ca9e"
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/gangadhar369/myapp-frontend
    tag: "4f9029657e3ae6472c6a985e78b19dc9e822ca9e"
    pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  user: postgres
  password: postgres
  database: appdb
  persistence:
    enabled: true
    size: 1Gi

