---
replicaCount: 1

image:
  backend:
    repository: docker.io/gangadhar369/myapp-backend
    tag: "b953de2431ac4face33dc6a40e80ffb9d0acbfac"
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/gangadhar369/myapp-frontend
    tag: "b953de2431ac4face33dc6a40e80ffb9d0acbfac"
    pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  user: postgres
  password: postgres
  database: appdb
  persistence:
    enabled: true
    size: 1Gi

