---
replicaCount: 1

image:
  backend:
    repository: docker.io/gangadhar369/myapp-backend
    tag: "a3040df2b9ba9606a3571fcd28519d1a9b5db2c3"
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/gangadhar369/myapp-frontend
    tag: "a3040df2b9ba9606a3571fcd28519d1a9b5db2c3"
    pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  user: postgres
  password: postgres
  database: appdb
  persistence:
    enabled: true
    size: 1Gi

