---
replicaCount: 1

image:
  backend:
    repository: docker.io/gangadhar369/myapp-backend
    tag: "8e934cd68a774d51d5106f6aaab164d84d733489"
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/gangadhar369/myapp-frontend
    tag: "8e934cd68a774d51d5106f6aaab164d84d733489"
    pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  user: postgres
  password: postgres
  database: appdb
  persistence:
    enabled: true
    size: 1Gi

