apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres

